# Generated by Django 5.1.5 on 2025-02-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255)),
                ('template_language', models.CharField(default='en_US', max_length=10)),
                ('template_category', models.CharField(choices=[('MARKETING', 'MARKETING'), ('UTILITY', 'UTILITY'), ('AUTHENTICATION', 'AUTHENTICATION')], max_length=50)),
                ('header_type', models.CharField(blank=True, choices=[('IMAGE', 'IMAGE'), ('TEXT', 'TEXT'), ('VIDEO', 'VIDEO'), ('FILE', 'FILE'), ('LOCATION', 'LOCATION')], max_length=50, null=True)),
                ('header_text', models.TextField(blank=True, null=True)),
                ('header_img_video_file_url', models.URLField(blank=True, null=True)),
                ('body_text', models.TextField()),
                ('footer_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_type', models.CharField(blank=True, choices=[('QUICK-REPLIES', 'QUICK-REPLIES'), ('CALLBACK', 'CALLBACK')], max_length=50, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('button_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('recipient_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('message_text', models.TextField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
